### ISSUE TITLE
divyam234/rclone can not show existing folders/files in windows.

### ISSUE THREAD

**Issue by akang943578** [tgdrive/teldrive#325]
I am using divyam234/rclone to mount teldrive on my Windows 10, but it's shown as empty after mounted, there are folders/files existing in teldrive, but shown as empty.
Newly added folders/files from windows can be found in teldrive, but existing folders/files before mounted can not shown in windows.

**Comment by vavtnen** [comment]
Are you using the latest rclone version?

**Comment by akang943578** [comment]
Yes, I was using rclone-v1.67.4-windows-amd64.zip

**Comment by akang943578** [comment]
> Have you verified all your files are there on the webui or verified in the database?

Yes, all files are there on webui, but existing files not on windows mounted by rclone.
If I created some folders or files from windows, the newly created folders/files are on both windows and webui.

**Comment by vavtnen** [comment]
It is very hard to figure out what is wrong without any log. The only thing I can think of is to clear rclone cache.
