### ISSUE TITLE
m4a audio files take forever to play

### ISSUE THREAD

**Issue by D0nnieD4rk0** [tgdrive/teldrive#335]
minor gripe but i think its something that should be looked into if possible. a 10 mb audio file shouldn't take 2 minutes to load. video files play just fine so its weird that audio is so cumbersome.

thanks

**Comment by Cohinem** [comment]
Umm I just uploaded and tried on the WebUI. they all start playing within 3-5 seconds. On what are you deploying your Teldrive instance?
