### ISSUE TITLE
Playing files

### ISSUE THREAD

**Issue by DaRKeN58** [tgdrive/teldrive#340]
Hi. Is anyone else experiencing the problem where no files are playing? I'm on Edge, I've tried Chrome and nothing. I don't know if I need to install something else or configure something extra, I've tried change the channel from "Private" to "Public" and nothing, it just doesn't load any type of file. I don't know what else to try, I need some help with this, thanks in advance.

Greetings.

**Comment by SingingDalong** [comment]
In my case, mp4 and mkv files can be played on the teldrive webpage. However, avi and ts files cannot be played. The browser uses Chrome.

**Comment by DaRKeN58** [comment]
> In my case, mp4 and mkv files can be played on the teldrive webpage. However, avi and ts files cannot be played. The browser uses Chrome.

In both Edge and Chrome only .mp3 and .m4a files are played but no video, I have tried mp4, mkv and nothing.

**Comment by SingingDalong** [comment]
> > In my case, mp4 and mkv files can be played on the teldrive webpage. However, avi and ts files cannot be played. The browser uses Chrome.
> 
> In both Edge and Chrome only .mp3 and .m4a files are played but no video, I have tried mp4, mkv and nothing.

Teldrive's media playback capabilities aren't perfect. We recommend mounting and streaming with rclone.

**Comment by joseavilasg** [comment]
@DaRKeN58 Try playing the file with VLC or a similar media player. If that doesn't work, then there might be an issue with the file or the uploading process.
