### ISSUE TITLE
failed to run SQL migration

### ISSUE THREAD

**Issue by lindasmith03** [tgdrive/teldrive#342]
I am trying to run it via docker image
docker pull ghcr.io/divyam234/teldrive:1.4.22

`docker run 27be7fe0ea35 --jwt-secret="test" --db-data-source="postgresql://user:pass@host/teledrive" --tg-app-hash=<hash> --tg-app-id=<id>`

`panic: failed run migrate: ERROR 20240711163538_search.sql: failed to run SQL migration: failed to execute SQL query "CREATE EXTENSION IF NOT EXISTS pgroonga;\nDROP INDEX IF EXISTS teldrive.name_search_idx;\nDROP FUNCTION IF EXISTS  teldrive.get_tsquery;\nDROP FUNCTION IF EXISTS teldrive.get_tsvector;\nCREATE INDEX name_search_idx ON teldrive.files USING pgroonga (REGEXP_REPLACE(name, '[.,-_]', ' ', 'g')) WITH (tokenizer = 'TokenNgram');": ERROR: could not open extension control file "/usr/local/share/extension/pgroonga.control": No such file or directory (SQLSTATE 58P01)`

Could amyone please help me.

**Comment by lindasmith03** [comment]
Hey @divyam234 could you please tell me how to use it without pgroonga extension as it is not available in some of the online serverless databases like neon and aiven.

**Comment by divyam234** [comment]
@lindasmith03  use supabase or local instance of postgres
