### ISSUE TITLE
Search result is always empty with an all-uppercase query

### ISSUE THREAD

**Issue by xd003** [tgdrive/teldrive#354]
I’m encountering an issue with file and folder searches. Specifically, when searching for files or folders with names in all uppercase, using an all-uppercase query does not return any results. However, if I use lowercase or a mix of uppercase and lowercase in the search query, the all-uppercase files or folders do appear in the search results, but they are listed lower down.

I'm unsure if this issue existed in earlier versions or if it's related to a recent update, as I didn't have the opportunity to test it previously.

**Comment by Linden10** [comment]
Ah I tested it out and got the same issue, all UPPER case search doesn't work!

This is what the console showed:

ERROR   PANIC: ERRORDATA_STACK_SIZE exceeded (SQLSTATE XX000)
ERROR   [DB] github.com/tgdrive/teldrive/pkg/services/file.go:334 PANIC: ERRORDATA_STACK_SIZE exceeded (SQLSTATE XX000)
ERROR   [DB] github.com/tgdrive/teldrive/pkg/services/file.go:334 FATAL: DbHandler exited (SQLSTATE XX000)
ERROR   FATAL: DbHandler exited (SQLSTATE XX000)

Using all capitals in the advanced search (as normal search did nothing with all captials) gave these errors.
However when I search with upper and lower case letters like usual it worked, yup!

Most likely an simple bug that needs a simple fix hopefully!
