### ISSUE TITLE
How to show what has already been uploaded from one Teldrive to another?

### ISSUE THREAD

**Issue by DaRKeN58** [tgdrive/teldrive#360]
Hello everyone. I wonder if anyone knows if this is possible. The thing is that I have Teldrive on a Windows 11 machine, everything works fine and I've already uploaded some files. But I've also mounted Teldrive on another machine that is more powerful, so to speak, with Linux. On both systems I use DBeaver and the same user and everything else.

So when I enter the Linux teldrive, everything works but it's empty. I've tried to enter the data by importing data from one DBeaver to another and it worked, the bots and channels load without errors but the "files" table even though enter the data with errors, the files are shown in the database. But, If I go to Teldrive they still don't appear on the home screen, with their folders and ordered as I have it on my Windows, only the files appear and are playable from "storage", but not on the home, it comes up empty.

Is there any way to have the same start with everything ordered? I don't mind starting from scratch since I've tried with few files. I hope I've explained myself well. And sorry for my English. Regards.

**Comment by SingingDalong** [comment]
I am using Postgrasql installed on an Oracle free VPS. No matter which computer you connect to, the DB is the same.
