### ISSUE TITLE
download speed very very slow

### ISSUE THREAD

**Issue by trovador01** [tgdrive/teldrive#377]
Hello, good morning, the following has happened to me for 2-3 days. I have a 2.2 GB movie on my Teldrive, and if I play the movie from the beginning it starts perfectly. But if I want to go to minute 59 it takes a long time to play again. I have noticed that the download speed has dropped a lot and I am a premium user.
I'm using bots and it happens to me both in teldrive web and in rclone.

**Comment by ViktorsBaikers** [comment]
It should be because of chunk'ing. I'm experiencing the same thing, but I don't think it could be fixed somehow. As your file is split into several small files, it might take a while.

**Comment by trovador01** [comment]
Having the last two versions of teldrive and rclone, 5 days ago it was much faster. Going to minute 59 took just 3 seconds, now it takes more than a minute. what could be happening?

**Comment by ViktorsBaikers** [comment]
Try the old version of teldrive. If that does not help, check if you've modified any config. If not, then maybe ***gram changed something on their end. Not quite sure, perhaps some more knowledged guys here could give you the correct answer.

As mentioned, i'm experiencing the same and was thinking that it's okysh

**Comment by doomwithdon** [comment]
I am on the latest teldrive version and I am not experiencing any such slowness using rcline.

**Comment by ViktorsBaikers** [comment]
> I am on the latest teldrive version and I am not experiencing any such slowness using rclone

Drop you settings of teldrive/rclone/mount, i will try from my end to replicate with your settings.

**Comment by trovador01** [comment]
I attach my settings


######teldrive - config.toml#######
[db]
  data-source = "XXXXXX"
  prepare-stmt = true
[db.pool]
    enable = true
    max-idle-connections = 25
    max-lifetime = "10m"
    max-open-connections = 25

[cronjobs]
  enable = true

[jwt]
  allowed-users = [""]
  secret = "XXXXXX"
  session-time = "30d"

[server]
  graceful-shutdown = "15s"
  port = XXXXX
  read-timeout = "1h"
  write-timeout = "1h"

[tg]
  app-hash = "XXXXXXXXX"
  app-id = XXXXXXX
  app-version = "4.6.3 K"
  bg-bots-limit = 5
  device-model = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"
  disable-stream-bots = false
  lang-code = "en"
  lang-pack = "webk"
  rate = 50
  rate-burst = 20
  rate-limit = true
  session-file = ""
  system-lang-code = "en-US"
  system-version = "Win32"
  
[tg.uploads]
    encryption-key = "XXXXXXXXX"
    retention = "7d"
    threads = 8

[tg.stream]
    multi-threads = 8
    buffers = 16


######rclone - rclone.conf#######
[data]
type = teldrive
api_host = http://localhost:XXXXX
access_token = XXXXXXXX
chunk_size = 500M
upload_concurrency = 4
encrypt_files = true
random_chunk_name = true


######rclone - mount#######
rclone mount data: E: --cache-dir --attr-timeout=8700h --use-mmap --stats=10s --buffer-size=32M --vfs-cache-poll-interval=30s --poll-interval=30s --dir-cache-time=8700h --vfs-cache-max-age=7720h --drive-server-side-across-configs --vfs-cache-mode=full --vfs-read-chunk-size=32M --vfs-read-chunk-size-limit=100G --vfs-read-chunk-size-limit=100G --vfs-read-chunk-streams=8 --vfs-cache-max-size=100G --local-no-check-updated --drive-chunk-size=64M --multi-thread-streams=4 --multi-thread-cutoff=250M --transfers=4 --timeout=30m --vfs-case-insensitive --drive-pacer-min-sleep=10ms --drive-pacer-burst=200

**Comment by ViktorsBaikers** [comment]
Thanks. Will try it out.

You can drop:
transfers -> It's default value.
drive-pacer-min-sleep, drive-pacer-burst, drive-server-side-across-configs, drive-chunk-size -> It won't work, it's only for GDrive.
poll-interval  -> I think it's not supported by teldrive.

**Comment by trovador01** [comment]
> Try the old version of teldrive. If that does not help, check if you've modified any config. If not, then maybe ***gram changed something on their end. Not quite sure, perhaps some more knowledged guys here could give you the correct answer.
> 
> As mentioned, i'm experiencing the same and was thinking that it's okysh

Does the same thing happen to you? Very slow speed?

**Comment by trovador01** [comment]
> > > I am on the latest teldrive version and I am not experiencing any such slowness using rclone
> > 
> > 
> > Drop you settings of teldrive/rclone/mount, i will try from my end to replicate with your settings.
> 
> config.toml: [db] data-source = "xxx" prepare-stmt = true
> 
> [db.pool] enable = true max-idle-connections = 25 max-lifetime = "10m" max-open-connections = 25
> 
> [jwt] secret = "www"
> 
> [tg] app-id = "aaa" app-hash = "xxx" bg-bots-limit = 5 disable-stream-bots = false rate = 50 rate-burst = 20 rate-limit = true
> 
> [cronjobs] enable = true
> 
> [server] graceful-shutdown = "15s" port = 8080 read-timeout = "1h" write-timeout = "1h"
> 
> [tg.uploads] threads = 8
> 
> [tg.stream] multi-threads = 8 buffers = 16 stream-buffers = 16
> 
> rclone mount: rclone mount --allow-other --allow-non-empty teldrive: /mnt/cloud
> 
> rclone config: [teldrive] type = teldrive access_token = xxx api_host = http://localhost:8080 chunk_size = 1800Mi #channel_id = -xxx upload_concurrency = 4 random_chunk_name = true threaded_streams = true

I have configured teldrive's .conf as you have indicated and rclone with the mount you have indicated and nothing, I am still the same.
It may be that telegram has slowed down a lot when detecting this system. In total I have uploaded about 200 movies but with a maximum size of 2gb.

**Comment by ViktorsBaikers** [comment]
> > Try the old version of teldrive. If that does not help, check if you've modified any config. If not, then maybe ***gram changed something on their end. Not quite sure, perhaps some more knowledged guys here could give you the correct answer.
> > As mentioned, i'm experiencing the same and was thinking that it's okysh
> 
> Does the same thing happen to you? Very slow speed?

Not the speed, but I'm experiencing the same with loading, when for example strolling to X minute, then i'm waiting kinda long to proceed with playback.

**Comment by trovador01** [comment]
> > > Try the old version of teldrive. If that does not help, check if you've modified any config. If not, then maybe ***gram changed something on their end. Not quite sure, perhaps some more knowledged guys here could give you the correct answer.
> > > As mentioned, i'm experiencing the same and was thinking that it's okysh
> > 
> > 
> > Does the same thing happen to you? Very slow speed?
> 
> Not the speed, but I'm experiencing the same with loading, when for example strolling to X minute, then i'm waiting kinda long to proceed with playback.
> 
> The main difference in the settings is the encryption, but hard to belive that it would make such big impact.

When you say wait a bit, how many seconds is that? In a 2gb file, if I go to the end of the video, it takes 45 seconds.

**Comment by ViktorsBaikers** [comment]
So was playing around with settings and found the root cause of it. It does such slowness if you use `encryption-key` in teldrive and `encrypt_files` in rclone together. Once i've commented out `encrypt_files` and uploaded file - everything works properly. 

Note: It will not fix your old files, you will mostly need to re-upload them.

**Comment by ViktorsBaikers** [comment]
Also, just tried on fresh teldrive instance. Same issue. So i can confirm on 100%, that's because of encryption.

**Comment by divyam234** [comment]
Encryption doesn't cause that much cpu usage could be server issue as I am getting almost same speed with encryption around 100MBps.

**Comment by ViktorsBaikers** [comment]
> Encryption doesn't cause that much cpu usage could be server issue as I am getting almost same speed with encryption around 100MBps.

Mostly it's not about the speed, but when you scroll encrypted video to let's say 30 min out of 1h, then for example for me the playback start after ~ 3 minutes of waiting. I've replicated on several machines this. Same issue and happens **ONLY** while file in encrypted. Redis didn't helped tho.

**Comment by divyam234** [comment]
Haven't faced this I have multiple encrypted video and all of them are playing smoothly with seeking .You need to enable vfs-chunk-streams also  for smooth playback  see more in wiki for recommend values

**Comment by ViktorsBaikers** [comment]
> Haven't faced this I have multiple encrypted video and all of them are playing smoothly with seeking .You need to enable `vfs-chunk-streams` also for smooth playback _see_ more in wiki for recommend values

I'm not first year into this, so indeed it has been done. It doesn't matter is it plex or teldrive UI, the issue is the same.

**Comment by dragoneroxx** [comment]
My speed download from rclone is max 4 mb/s but this is not so good (upload speed is good)

![rclone](https://i.imgur.com/8gLoqNn.png)

my rclone.conf is this

```
[teldrive]
type = teldrive
api_host = http://localhost:8080
access_token = **************
chunk_size = 200M
upload_concurrency = 4
encrypt_files = false
random_chunk_name = true
root_folder_id = 01968a4a-b41d-76a3-80f1-**********
```

I use a .bat file to start teldrive with rclone and I have this

```
@echo off
cd /d C:\Users\jack9\.installer\bin

REM 1) Start TelDrive
start "" teldrive.exe run --config .\config.toml

REM 2) Wait 5 seconds
timeout /t 5 >nul

set "CACHE_DIR=%LOCALAPPDATA%\rclone-cache"
if not exist "%CACHE_DIR%" mkdir "%CACHE_DIR%"

REM 3) Mount rclone
start "RClone Mount" /min rclone.exe --config rclone.conf ^
  mount teldrive: Z: ^
  --vfs-cache-mode full ^
  --cache-dir "%CACHE_DIR%" ^
  --dir-cache-time 72h ^
  --attr-timeout 1h ^
  --vfs-cache-max-size 50G ^
  --vfs-cache-max-age 24h ^
  --buffer-size 128M ^
  --vfs-read-chunk-size 128M ^
  --vfs-read-chunk-size-limit 2G ^
  --poll-interval 15m ^
  --links ^
  --vfs-refresh ^
  --rc --rc-addr 127.0.0.1:5572 --rc-no-auth ^
  --log-level INFO ^
  --log-file "%CACHE_DIR%\rclone.log"
```

my config.toml is this

```
[db]
data-source = "postgres://postgres:**********@db.*****************.supabase.co:5432/postgres"
prepare-stmt = false

[db.pool]
enable = false

[jwt]
allowed-users = ["***********"]
secret = "**********************"

[tg.uploads]
encryption-key = "******************"

[server]
address = "127.0.0.1"
port = 8080
```

I am a premium user on telegram
Any idea to improve download speed from rclone ?

**Comment by ViktorsBaikers** [comment]
@dragoneroxx vfs-read-chunk-size 128M is quite high and also you should set vfs-read-chunk-streams. 

In my setup im using:

```
--vfs-read-chunk-streams 16 \
--vfs-read-chunk-size 8M \
```

**Comment by dragoneroxx** [comment]
> [@dragoneroxx](https://github.com/dragoneroxx) vfs-read-chunk-size 128M is quite high and also you should set vfs-read-chunk-streams.
> 
> In my setup im using:
> 
> ```
> --vfs-read-chunk-streams 16 \
> --vfs-read-chunk-size 8M \
> ```

please look this video
https://mega.nz/file/85BxEaoR#AbHQTIgrDGFb3T6pKNsB37CgUhqkyPWJIWHpTJ4JBTc

i set up in this way now but speed is slow and transfer rate is erratic, with sudden spikes and drops

```
@echo off
cd C:\Users\jack9\.installer\bin

REM 1) Start TelDrive
start "" teldrive.exe run --config .\config.toml

REM 2) Wait 5 seconds
timeout 5 >nul

set "CACHE_DIR=%LOCALAPPDATA%\rclone-cache"
if not exist "%CACHE_DIR%" mkdir "%CACHE_DIR%"

REM 3) Mount rclone
start "RClone Mount" rclone.exe --config rclone.conf ^
  mount teldrive: Z: ^
  --vfs-cache-mode=full ^
  --cache-dir="%CACHE_DIR%" ^
  --dir-cache-time=2h ^
  --attr-timeout=1h ^
  --vfs-cache-max-size=200G ^
  --vfs-cache-max-age=24h ^
  --buffer-size=32M ^
  --vfs-read-chunk-size=8M ^
  --vfs-read-chunk-size-limit=off ^
  --vfs-read-chunk-streams=16 ^
  --teldrive-threaded-streams=1 ^
  --umask=002 ^
  --allow-other ^
  --allow-non-empty ^
  --no-checksum ^
  --rc ^
  --rc-addr=127.0.0.1:5572 ^
  --rc-no-auth ^
  --log-level=INFO ^
  --log-file="%CACHE_DIR%\rclone.log"
```
