### ISSUE TITLE
[Bug]: channel_id not updated after replacing a file on different channel

### ISSUE THREAD

**Issue by danieleg1** [tgdrive/teldrive#388]
### Describe the bug

When an existing file is replaced to another channel, the channel_id in the database is not updated.

### Repoduction

In rclone.conf set channel_id as Channel_A
Upload a file
Modify the local file
In rclone.conf change channel_id to Channel_B
Reupload the file

### Expected behavior

After the file is replaced I expected that the channel_id in the database to be Channel_B, but I see that is still Channel_A. This was the cause of duplicated ids on the database.

### Version

[1.5.3](https://github.com/tgdrive/teldrive/commits/1.5.3)

### Which Platform are you using?

Linux

### Additional context

rclone v1.68.1

**Comment by divyam234** [comment]
@danieleg1 should be working in latest builds of teldrive and rclone

**Comment by danieleg1** [comment]
Upgraded both teldrive and rclone, now is working as expected. Thank you!
