### ISSUE TITLE
[feat] AARCH64 INSTALLER

### ISSUE THREAD

**Issue by ss-iptv** [tgdrive/teldrive#405]
I found this issue:

curl -sSL https://instl.vercel.app/tgdrive/teldrive/linux | bash
 i Found latest release of teldrive (version: 1.5.6)
 i Found 9 assets in '1.5.6' - searching for one that fits your system...
 X Unsupported architecture: aarch64

Unsupported architecture: aarch64

**Comment by divyam234** [comment]
```
curl -s "https://sh-install.vercel.app/tgdrive/teldrive?move=1"  | bash
```
You can also use this which will work for all arches only works on linux.
