### ISSUE TITLE
Emby doesnt play a single file

### ISSUE THREAD

**Issue by r0gu3ptm** [tgdrive/teldrive#69]
So moved a few files into teldrive, so far so good, emby cant play them, all im getting are the errors below:
r0gu3@server3:/etc/systemd/system$ sudo systemctl status teldrive_vfs.service
● teldrive_vfs.service - Rclone VFS Mount
   Loaded: loaded (/etc/systemd/system/teldrive_vfs.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2023-12-03 21:54:09 CET; 43s ago
  Process: 12080 ExecStop=/bin/fusermount -uz /mnt/teldrive (code=exited, status=0/SUCCESS)
  Process: 12082 ExecStartPre=/bin/sleep 10 (code=exited, status=0/SUCCESS)
 Main PID: 12154 (rclone)
   Status: "[21:54] vfs cache: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)"
    Tasks: 12 (limit: 4915)
   CGroup: /system.slice/teldrive_vfs.service
           └─12154 /usr/bin/rclone mount --user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70 --config=/home/r0gu3/.config/rclone/rclone.conf --all

Dec 03 21:54:53 server3 rclone[12154]: Media/Filme.Romanesti/Queen.Marie.of.Romania.2019.1080p.AMZN.WEB-DL.DDP.5.1.H.264-SPWEB.mkv: vfs cache: too many errors 11/10: last error: vfs reader: failed to write to cache file: HTTP error 416 (
Dec 03 21:54:53 server3 rclone[12154]: Media/Filme.Romanesti/Queen.Marie.of.Romania.2019.1080p.AMZN.WEB-DL.DDP.5.1.H.264-SPWEB.mkv: vfs cache: failed to kick waiters: vfs reader: failed to write to cache file: HTTP error 416 (416 Request
Dec 03 21:54:53 server3 rclone[12154]: Media/Filme.Romanesti/Queen.Marie.of.Romania.2019.1080p.AMZN.WEB-DL.DDP.5.1.H.264-SPWEB.mkv: vfs cache: failed to _ensure cache vfs reader: failed to write to cache file: HTTP error 416 (416 Request
Dec 03 21:54:53 server3 rclone[12154]: IO error: vfs reader: failed to write to cache file: HTTP error 416 (416 Requested Range Not Satisfiable) returned body: "invalid range: failed to overlap\n"
Dec 03 21:54:53 server3 rclone[12154]: Media/Filme.Romanesti/Queen.Marie.of.Romania.2019.1080p.AMZN.WEB-DL.DDP.5.1.H.264-SPWEB.mkv: vfs cache: downloader: error count now 12: vfs reader: failed to write to cache file: HTTP error 416 (416
Dec 03 21:54:53 server3 rclone[12154]: Media/Filme.Romanesti/Queen.Marie.of.Romania.2019.1080p.AMZN.WEB-DL.DDP.5.1.H.264-SPWEB.mkv: vfs cache: failed to download: vfs reader: failed to write to cache file: HTTP error 416 (416 Requested R
Dec 03 21:54:53 server3 rclone[12154]: Media/Filme.Romanesti/Queen.Marie.of.Romania.2019.1080p.AMZN.WEB-DL.DDP.5.1.H.264-SPWEB.mkv: vfs cache: too many errors 12/10: last error: vfs reader: failed to write to cache file: HTTP error 416 (
Dec 03 21:54:53 server3 rclone[12154]: Media/Filme.Romanesti/Queen.Marie.of.Romania.2019.1080p.AMZN.WEB-DL.DDP.5.1.H.264-SPWEB.mkv: vfs cache: failed to kick waiters: vfs reader: failed to write to cache file: HTTP error 416 (416 Request
Dec 03 21:54:53 server3 rclone[12154]: Media/Filme.Romanesti/Queen.Marie.of.Romania.2019.1080p.AMZN.WEB-DL.DDP.5.1.H.264-SPWEB.mkv: vfs cache: failed to _ensure cache vfs reader: failed to write to cache file: HTTP error 416 (416 Request
Dec 03 21:54:53 server3 rclone[12154]: IO error: vfs reader: failed to write to cache file: HTTP error 416 (416 Requested Range Not Satisfiable) returned body: "invalid range: failed to overlap\n"

I am on the latest teldrive and did the database update on neon

**Comment by xd003** [comment]
Facing the same issue myself, all videos play fine in teldrive web ui but nothing plays in emby. I am gonna test with jellyfin too just in case to confirm before concluding that its a streaming issue with rclone mount only

**Comment by r0gu3ptm** [comment]
> Facing the same issue myself, all videos play fine in teldrive web ui but nothing plays in emby. I am gonna test with jellyfin too just in case to confirm before concluding that its a streaming issue with rclone mount only

You are lucky, i just uploaded files that play just fine locally with emby, they dont play at all in teldrive ui; I have never made it work to stream from teldrive into emby; im not sure if this is something to do with teldrive or how i made the configs to be honest.

**Comment by r0gu3ptm** [comment]
Oh ? What flags are required if you dont mind ?

**Comment by xd003** [comment]
rclone mount teldrive: /mnt/rclone --vfs-cache-mode=full  -vfs-cache-max-age=72h --vfs-cache-max-size=200G

This should be fine

**Comment by r0gu3ptm** [comment]
Thank you very much, i will test that right away.

**Comment by aniel300** [comment]
@xd003 i cant get it to work can u help me?
